//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doing
    {
        public int Id { get; set; }
        public string Doing1 { get; set; }
        public int UserId { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
